name: Create APK from Master

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK ⚙️🛠
      run: bash ./gradlew assembleProductionDebug
 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: app/build/outputs/apk/production/debug/*.apk
      
